In [1]:
import numpy as np
from mc import MC as MC
import random

# Markov Chain Approach applied to DNA Mutation

Mutation of nucleotides may be modeled based on specift transition probabilitiyes to perform nucleotide-to-nucleotide mutations. One can imagince that hte the probability of substituing A by C in the DNA Chan may be prescribed as (say) 0.4. One needs to construct a transition probability to be able to describe all the possible mutations laong the DNA chainge. This statistical evolution is known as a Markov process or Markov chain.
The module I developed (MC) permits to change the DNA chains with a Markov Chain method,a process that can be  described as follows:
(1) We first create a DNA chain AGTGTT.. 
(2) The we modify (mutate) the DNA sequences : For this end we create a transition matrix 
(3) Then we perform a define numbers of mutation attemps on the DNA chain

In [2]:


#First create the MC objec
dna_Markov_Chain = MC(  seed = 2)


Let's create the DNA Chain. It is a list of 0 (A) , 1 (C) , 2(G) ,3 (T)

In [43]:
dna_chain = np.random.randint(4, size=20)

In [44]:
dna_chain

array([3, 1, 3, 2, 1, 0, 3, 1, 3, 2, 0, 3, 0, 0, 1, 1, 2, 1, 0, 2])

Let's Create the transition (mutation) probability matrix

In [45]:
#Lets create transition probability matrix
Mutation_Matrix = np.random.random_sample((4,4))

for idx,row in enumerate(Mutation_Matrix):
    norm = np.sum(row**2.0)**0.5
    
    norm = 1./ norm
    row = row * norm
    Mutation_Matrix[idx] = row



dna_Markov_Chain.set_adjmatrix(Mutation_Matrix)

[[ 0.48577178  0.54649216  0.12209685  0.67116649]
 [ 0.12218597  0.74104286  0.5919929   0.29235333]
 [ 0.68635248  0.53530389  0.04978412  0.48978727]
 [ 0.30781054  0.60745912  0.5816702   0.44486612]]


In [46]:

#Function To transform dna chain from numbers to letters (nucleotides)

def trans_to_letters(nbr_dna):
    #create list buffer to store nucleotides letters
    dna_letters = []
    # dictionary to trnasform numbers to letter
    trans_keys = {0:'A',1:'C', 2:'G',3:'T' }
    
    # loop through dna chain to transform to letters
    for seq in nbr_dna: 
        new_letter = trans_keys[seq]
        dna_letters.append(new_letter)
    
    #return join dna chain represented by letters
    
    return ''.join(dna_letters)



Let's perform some mutations to the DNA chain with a MArkov Chain Model

In [50]:

n_mutations = 100; #number of mutation attemps
#track old chain
old_dna_chain = np.array(dna_chain );
old_dna_chain = trans_to_letters(old_dna_chain);
for i in range(n_mutations):
    
    base = random.randint(0, len(dna_chain)-1)
    base  = dna_chain[base]
    dna_chain[base] = dna_Markov_Chain.compute_transition(base)
    print("**********mutation attempt: %s************" %i)
    print("old_dna_chain: %s"% old_dna_chain)
    print("new_dna_chain: %s"% trans_to_letters(dna_chain))


Node argument is not of integer type: Attemp to transform to integer was performed but it may have failed
**********mutation attempt: 0************
old_dna_chain: CCCCCATCTGATAACCGCAG
new_dna_chain: CCACCATCTGATAACCGCAG
Node argument is not of integer type: Attemp to transform to integer was performed but it may have failed
**********mutation attempt: 1************
old_dna_chain: CCCCCATCTGATAACCGCAG
new_dna_chain: CCACCATCTGATAACCGCAG
Node argument is not of integer type: Attemp to transform to integer was performed but it may have failed
**********mutation attempt: 2************
old_dna_chain: CCCCCATCTGATAACCGCAG
new_dna_chain: CCACCATCTGATAACCGCAG
Node argument is not of integer type: Attemp to transform to integer was performed but it may have failed
**********mutation attempt: 3************
old_dna_chain: CCCCCATCTGATAACCGCAG
new_dna_chain: CCACCATCTGATAACCGCAG
Node argument is not of integer type: Attemp to transform to integer was performed but it may have failed
**********muta